defmodule SurfaceEject.HooksIndex do
  @moduledoc """
  Surface-independent collector for colocated JS hooks.

  Surface's compiler generates `hooks/index.js` from modules that still `use Surface.*`, as modules are converted they silently drop out of the collection and their hooks break. This regenerates the SAME artifact (module-named copies plus an `ns()`-namespaced `index.js`, byte-compatible with Surface's output format) from a plain file glob, so registered hook names (`Module.Name#hook`) and bundler wiring stay untouched for converted and unconverted modules alike.

  Run it AFTER any Surface compile (whose output it overwrites with the complete set), e.g. via the escript: `./surface_eject hooks-index --path extensions --out config/current_flavour/assets/hooks`.
  """

  alias SurfaceEject.{Context, Files, Scan}

  @doc """
  Collects `*.hooks.js` under `roots` (default exclusions pruned), resolves each module from the colocated `.ex` sibling, copies them as `<Module>.hooks.js` into `out_dir`, and writes `index.js`.

  Returns `{:ok, %{copied: [module], skipped: [path]}}`.
  """
  def generate(roots, out_dir) do
    {resolved, skipped} =
      roots
      |> Enum.flat_map(&Files.list_files(&1, [], [".js"]))
      |> Enum.filter(&String.ends_with?(&1, ".hooks.js"))
      |> Enum.map(fn path -> {path, module_for(path)} end)
      |> Enum.split_with(fn {_path, module} -> is_binary(module) end)

    resolved = Enum.sort_by(resolved, fn {_path, module} -> module end)

    File.mkdir_p!(out_dir)

    for {path, module} <- resolved do
      File.cp!(path, Path.join(out_dir, "#{module}.hooks.js"))
    end

    File.write!(Path.join(out_dir, "index.js"), index_js(Enum.map(resolved, &elem(&1, 1))))

    {:ok, %{copied: Enum.map(resolved, &elem(&1, 1)), skipped: Enum.map(skipped, &elem(&1, 0))}}
  end

  # `foo.hooks.js` → module of the colocated `foo.ex`
  defp module_for(path) do
    sibling = String.replace_suffix(path, ".hooks.js", ".ex")

    with true <- File.exists?(sibling),
         %{module: module} when is_binary(module) <-
           Scan.scan_source(File.read!(sibling), %Context{file: sibling}) do
      module
    else
      _ -> nil
    end
  end

  defp index_js(modules) do
    imports =
      modules
      |> Enum.with_index(1)
      |> Enum.map_join("\n", fn {module, i} ->
        ~s(import * as c#{i} from "./#{module}.hooks.js")
      end)

    entries =
      modules
      |> Enum.with_index(1)
      |> Enum.map_join(",\n", fn {module, i} -> ~s(  ns\(c#{i}, "#{module}"\)) end)

    """
    /*
    This file was generated by surface_eject (hooks-index). Do not edit by hand.
    */

    function ns(hooks, nameSpace) {
      const updatedHooks = {}
      Object.keys(hooks).map(function(key) {
        updatedHooks[`${nameSpace}#${key}`] = hooks[key]
      })
      return updatedHooks
    }

    #{imports}

    let hooks = Object.assign(
    #{entries}
    )

    export default hooks
    """
  end
end